
exports.up = knex => knex.schema.createTable('profile_values', t => {
  t.bigIncrements('id').primary().unsigned()
  t.integer('profile_id')
    .references('profiles.id')
    .unsigned()
    .index()
    .notNullable()
    .onDelete('CASCADE')
  t.timestamp('datetime').notNullable()
  t.float('value').notNullable()
  t.float('depth_m').notNullable()
  t.text('flag_id')
    .references('flags.id')
    .unsigned()
    .index()
    .notNullable()
    .onDelete('SET NULL')
  t.text('flag_other')
})

exports.down = knex => knex.schema.dropTable('profile_values')
