
exports.up = knex => knex.schema.createTable('series', t => {
  t.increments('id').primary().unsigned()
  t.integer('file_id')
    .references('files.id')
    .unsigned()
    .index()
    .notNullable()
    .onDelete('CASCADE')
  t.integer('station_id')
    .references('stations.id')
    .unsigned()
    .index()
    .notNullable()
    .onDelete('CASCADE')

  t.float('depth_m')
  t.text('depth_category')
  t.timestamp('start_datetime')
  t.timestamp('end_datetime')
  t.text('interval')
  t.float('frequency')
  t.boolean('reviewed')
  t.integer('accuracy')
  t.boolean('sop_bath')

  t.timestamps(true, true)
})

exports.down = knex => knex.schema.dropTable('series')
